---
layout: cv
title: Cian McShane's CV
---
# Cian McShane

(Email)[cian.mcshane@icloud.com]
(My Linkedin)[https://www.linkedin.com/in/cian-mcshane-13842a36a/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3B3RIJ8jb4TMSBAPU7lk5T9A%3D%3D]


## Currently

Studying data science at Brigham Young University-Idaho`


## Education

`2018-2022`
__Richland High School__

`September 2024 - now`
__Brigham Young University-Idaho__



## Publications

[My Greatest Accomplishment](https://www.youtube.com/watch?v=xvFZjo5PgG0)

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->


## Occupation

`2024-2025`
__Starbucks__, Richland, WA

- Prepared and served beverages and food items
- Provided excellent customer service to ensure a positive experience

`April 2017 - August 2020`
__Masters Lawn Care__, Kennewick, WA

- Mowed, edged, and trimmed lawns for residential and commercial clients, ensuring a clean,manicured appearance, Monday through Saturday
- Applied fertilizers, weed control products, and pesticides to promote healthy lawns and preventunwanted plant growth, and removed weeds


## Skills

- Programming & Data Analysis: Python, R, SQL, Excel, Pandas, NumPy

- Statistical Analysis: Hypothesis testing, regression, probability


<!-- ### Footer

Last updated: May 2013 -->